title: "Cyrill Schumacher's Blog"
languageCode: "en-gb"
copyright: "Copyright (c) 2014-2016, Cyrill Schumacher; all rights reserved."
MetaDataFormat: "yaml"
canonifyURLs: true
builddrafts: false
timeout: 600000
Paginate: 7
paginatePath: paginator
permalinks:
  posts: /:year/:month/:day/:title/
taxonomies:
  tag: "tags"
  category: "categories"
params:
  CopyrightHTML: "Copyright &#xA9; 2014-2016 Cyrill Schumacher. All Rights Reserved."
  GitHubUser: "schumacherfm"
  SidebarRecentLimit: 5
  Categories:
    - "Thoughts"
    - "Projects"
    - "Imprint"
images:
  - 480x
  - 768x
  - 960x
  - 1024x
  - 1920x
  - 720x340
  - 520x245
