[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[build]
publish = "public"
command = "hugo -v --minify -b https://cyrillschumacher.com/"

[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo -v --minify --enableGitInfo -b https://cyrillschumacher.com/"

[context.split1.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.80.0"

[context.branch-deploy]
command = "hugo --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "รง"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
